name: cstar-env
channels:
  - conda-forge
dependencies:
  - python>=3.12,<3.14
  - pip
  - roms-tools>=5.0,<6
  # forge application runtime dependencies
  - jinja2
  - pandas
  - copernicusmarine
  - gdown
  - dask
  - distributed
  - threadpoolctl
  - numba
  - fsspec
  - kerchunk
  - nest-asyncio
  - ujson
  - fastparquet
  - xarray
  # wizard (cstar.wizard) runtime dependencies
  - ipywidgets
  - voila
  - jupyterlab
  - matplotlib-base
  - ipython
  # docs builds only
  - pandoc
