"""Register a Jupyter kernel for the active conda/micromamba environment.

Backs ``cstar forge register-kernel`` (cstar_forge/cli.py), which
dev-setup.sh also invokes after installing the package. Registers (or
repairs) a user-level kernelspec, then rewrites its kernel.json to launch
through a small activation wrapper (start-kernel.sh) instead of the env's
bare python path.

Why the wrapper: a Jupyter server hosted outside the env (e.g. an HPC
OnDemand portal) launches kernels with none of the env's PATH or activate.d
hook vars (PROJ_DATA, GDAL_DATA, ...), so subprocesses (``!cmd``, shell
magics) and activate.d-dependent packages break even though in-notebook
Python imports still work.
"""

import json
import os
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

WRAPPER_FILENAME = "start-kernel.sh"

PACKAGE_MANAGERS = ("auto", "micromamba", "conda", "mamba")


class RegisterKernelError(RuntimeError):
    """A kernel-registration precondition failed; the message is user-facing."""


# Wrapper templates are .format()-ed; bash's own braces (the FI_PROVIDER
# parameter expansion) are doubled to survive it, and "$@" / "$(...)" contain
# no braces so they pass through verbatim.
#
# FI_PROVIDER: the first xESMF regrid in a wizard/notebook kernel initializes
# ESMF/MPI, and libfabric's default "sockets" provider then busy-polls at
# ~100% CPU per progress thread (macOS) for the life of the kernel; the tcp
# provider services the same single-process MPI without spinning. Default it
# here (a pre-set value wins) -- batch ROMS runs launched outside Jupyter
# keep their own default.
_MICROMAMBA_WRAPPER = """\
#!/usr/bin/env bash
# Auto-generated by `cstar forge register-kernel`. Activates the micromamba
# env before starting the kernel so subprocesses inherit PATH and activate.d
# hook vars.
set -eo pipefail
eval "$({micromamba_bin} shell hook --shell bash)"
micromamba activate "{env_prefix}"
# Keep the kernel off user-site (~/.local) so it cannot shadow the env packages.
export PYTHONNOUSERSITE=1
# Spin-free libfabric provider for in-kernel ESMF/MPI (see register_kernel.py).
export FI_PROVIDER="${{FI_PROVIDER:-tcp}}"
# Drop any PYTHONPATH inherited from the hosting Jupyter server: HPC portals
# (e.g. OnDemand) export their own jupyter/pyzmq module trees, built for a
# different Python, and PYTHONPATH outranks the env's site-packages.
unset PYTHONPATH
exec python -m ipykernel_launcher "$@"
"""

_CONDA_WRAPPER = """\
#!/usr/bin/env bash
# Auto-generated by `cstar forge register-kernel`. Activates the conda env
# before starting the kernel so subprocesses inherit PATH and activate.d
# hook vars.
set -eo pipefail
source "{conda_base}/etc/profile.d/conda.sh"
conda activate "{env_prefix}"
# Keep the kernel off user-site (~/.local) so it cannot shadow the env packages.
export PYTHONNOUSERSITE=1
# Spin-free libfabric provider for in-kernel ESMF/MPI (see register_kernel.py).
export FI_PROVIDER="${{FI_PROVIDER:-tcp}}"
# Drop any PYTHONPATH inherited from the hosting Jupyter server: HPC portals
# (e.g. OnDemand) export their own jupyter/pyzmq module trees, built for a
# different Python, and PYTHONPATH outranks the env's site-packages.
unset PYTHONPATH
exec python -m ipykernel_launcher "$@"
"""


def _env_prefix() -> Path:
    """The running interpreter's env prefix, verified to be a conda-like env.

    Deriving the prefix from ``sys.prefix`` (rather than trusting whatever
    ``python`` is on PATH, as the old shell script had to) is what makes the
    registered kernel point at the right env by construction.
    """
    prefix = Path(sys.prefix)
    if not (prefix / "conda-meta").is_dir():
        raise RegisterKernelError(
            f"the running python ({sys.executable}) is not inside a "
            "conda/micromamba environment, so there is no env to register a "
            "kernel for. Activate the target env and re-run from it."
        )
    return prefix


def detect_package_manager(preferred: str = "auto") -> str:
    """Pick the tool the activation wrapper should use."""
    if preferred not in PACKAGE_MANAGERS:
        raise RegisterKernelError(
            f"unknown package manager {preferred!r} (expected one of "
            f"{', '.join(PACKAGE_MANAGERS)})"
        )
    if preferred == "mamba":
        # mamba envs activate through conda.sh; the wrapper has no mamba branch.
        return "conda"
    if preferred != "auto":
        return preferred
    if shutil.which("micromamba"):
        return "micromamba"
    if shutil.which("conda") or os.environ.get("CONDA_EXE"):
        return "conda"
    raise RegisterKernelError(
        "neither micromamba nor conda was found on PATH; pass "
        "--package-manager (and --micromamba-bin if needed) explicitly."
    )


def _conda_base() -> str:
    """Locate the conda base install the wrapper must source conda.sh from."""
    try:
        out = subprocess.run(
            ["conda", "info", "--base"], capture_output=True, text=True, check=True
        ).stdout.strip()
        if out:
            return out
    except (OSError, subprocess.CalledProcessError):
        pass
    conda_exe = os.environ.get("CONDA_EXE")
    if conda_exe:
        return str(Path(conda_exe).parents[1])
    raise RegisterKernelError(
        "could not determine the conda base install (`conda info --base` "
        "failed and CONDA_EXE is unset). Re-run from a shell where conda is "
        "initialized (e.g. after 'module load conda')."
    )


def build_wrapper_content(
    package_manager: str,
    env_prefix: Path,
    *,
    micromamba_bin: str = "micromamba",
    conda_base: str | None = None,
) -> str:
    """Render the start-kernel.sh wrapper for the given package manager."""
    if package_manager == "micromamba":
        # Absolute path where possible: the external Jupyter server that runs
        # this wrapper won't have the user's PATH.
        resolved = shutil.which(micromamba_bin) or micromamba_bin
        return _MICROMAMBA_WRAPPER.format(
            micromamba_bin=resolved, env_prefix=env_prefix
        )
    if package_manager == "conda":
        return _CONDA_WRAPPER.format(
            conda_base=conda_base if conda_base is not None else _conda_base(),
            env_prefix=env_prefix,
        )
    raise RegisterKernelError(f"unknown package manager {package_manager!r}")


def rewrite_kernel_json(kernel_dir: Path, wrapper_path: Path) -> None:
    """Point kernel.json at the wrapper, preserving display_name/language/metadata.

    {connection_file} must stay a literal Jupyter template placeholder.
    """
    kernel_json_path = kernel_dir / "kernel.json"
    spec = json.loads(kernel_json_path.read_text())
    spec["argv"] = [str(wrapper_path), "-f", "{connection_file}"]
    kernel_json_path.write_text(json.dumps(spec, indent=1))


def _install_kernelspec(name: str, display_name: str) -> Path:
    """Install the user-level kernelspec via ipykernel; returns its directory."""
    try:
        from ipykernel.kernelspec import install as ipykernel_install
    except ImportError as exc:
        raise RegisterKernelError(
            "ipykernel is not installed in this environment. It ships with "
            "the conda-forge `cstar-forge` package and with `pip install "
            "'cstar-forge[app]'`."
        ) from exc
    return Path(
        ipykernel_install(user=True, kernel_name=name, display_name=display_name)
    )


def _remove_kernelspec(name: str) -> bool:
    """Remove an existing kernelspec named ``name``; returns whether one existed."""
    from jupyter_client.kernelspec import KernelSpecManager

    ksm = KernelSpecManager()
    if name not in ksm.find_kernel_specs():
        return False
    ksm.remove_kernel_spec(name)
    return True


def register_kernel(
    *,
    name: str | None = None,
    display_name: str | None = None,
    clean: bool = False,
    package_manager: str = "auto",
    micromamba_bin: str = "micromamba",
    log: Callable[[str], None] = print,
) -> Path:
    """Register (or repair) the env's Jupyter kernel; returns the kernelspec dir.

    Always (re)installs, so re-running also repairs kernels registered by
    older versions of this tooling (ipykernel install overwrites in place,
    keeping this idempotent). ``clean`` removes the existing kernelspec dir
    first, discarding any stale files in it.
    """
    env_prefix = _env_prefix()
    name = name or env_prefix.name
    display_name = display_name or name
    manager = detect_package_manager(package_manager)

    # Render the wrapper before touching the kernelspec, so a missing conda
    # base fails cleanly instead of leaving a half-repaired kernel behind.
    wrapper_content = build_wrapper_content(
        manager, env_prefix, micromamba_bin=micromamba_bin
    )

    if clean and _remove_kernelspec(name):
        log(f"Removed existing Jupyter kernel: {name}")

    log(f"Installing Jupyter kernel: {name}")
    kernel_dir = _install_kernelspec(name, display_name)

    wrapper_path = kernel_dir / WRAPPER_FILENAME
    log(f"Writing kernel activation wrapper: {wrapper_path}")
    wrapper_path.write_text(wrapper_content)
    wrapper_path.chmod(0o755)

    rewrite_kernel_json(kernel_dir, wrapper_path)
    log(f"✓ Kernel '{name}' registered to launch via activation wrapper")
    return kernel_dir
