FROM ubuntu:24.04 as main

ENV TERM="xterm-256color"

RUN apt-get update && \
    apt-get install -y \
        --no-install-recommends \
        binutils \
        build-essential \
        ca-certificates \
        gdal-bin \
        git-all \
        gfortran \
        libgdal-dev \
        libstdc++-14-dev \
        libxml2-dev \
        libcurl4-openssl-dev \
        m4 \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        python-is-python3 \
        rsync \
        software-properties-common \
	    wget \
        zlib1g-dev \
        libfabric-dev \
        libssl-dev autoconf automake libtool \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \


    ldconfig



COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD []
ENTRYPOINT ["/entrypoint.sh"]
