#mpich 4.2,2 for cpu
FROM ubuntu:24.04
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /tmp

RUN \
    apt-get update        && \
    apt-get install --yes    \
                    --no-install-recommends \
                    build-essential      \
                    python3-dev          \
                    gfortran             \
                    wget              && \
    apt-get install -y python3-pip && \
    apt-get clean all

ARG mpich=4.2.2
ARG mpich_prefix=mpich-$mpich

ARG ncpus $(( $nproc / 8 ))
RUN \
    wget https://www.mpich.org/static/downloads/$mpich/$mpich_prefix.tar.gz && \
    tar xvzf $mpich_prefix.tar.gz                                           && \
    cd $mpich_prefix                                                        && \
    ./configure                                                             && \
    make -j $ncpus                                                          && \
    make install                                                            && \
    make clean                                                              && \
    cd ..                                                                   && \
    rm -rf $mpich_prefix

RUN /sbin/ldconfig

