import shutil
from pathlib import Path
from typing import Final, Literal, override

from cstar.base.log import LoggingMixin


class JobFileSystem(LoggingMixin):
    """JobFileSystem establishes a common directory structure convention across
    all jobs.
    """

    INPUT_NAME: Literal["input"] = "input"
    WORK_NAME: Literal["work"] = "work"
    TASKS_NAME: Literal["tasks"] = "tasks"
    LOGS_NAME: Literal["logs"] = "logs"
    OUTPUT_NAME: Literal["output"] = "output"

    root: Final[Path]
    """The root directory of the job. It is provided via user configuration."""

    input_dir: Final[Path]
    """The directory for job inputs, such as datasets, code repositories, and
    runtime configuration.
    """

    work_dir: Final[Path]
    """The directory for job work items, such as shell scripts generated by the
    system."""

    tasks_dir: Final[Path]
    """The directory for subtasks of a job, such as automatic system tasks
    or those generated via transformations of the inputs."""

    logs_dir: Final[Path]
    """The directory for log files created during the job."""

    output_dir: Final[Path]
    """The directory for writing any outputs from the job."""

    def __init__(self, root_directory: Path) -> None:
        """Initialize the job file system.

        Parameters
        ----------
        root_directory : Path
            The root directory that contains all job byproducts.
        """
        self.root = root_directory
        self.input_dir = self.root / self.INPUT_NAME
        self.work_dir = self.root / self.WORK_NAME
        self.tasks_dir = self.root / self.TASKS_NAME
        self.logs_dir = self.root / self.LOGS_NAME
        self.output_dir = self.root / self.OUTPUT_NAME

    def _dir_set(self) -> set[Path]:
        """Return the complete set of directories for the job.

        Returns
        -------
        set[Path]
        """
        return {
            self.input_dir,
            self.work_dir,
            self.tasks_dir,
            self.logs_dir,
            self.output_dir,
        }

    def prepare(self) -> None:
        """Construct the directory tree for the job."""
        for task_dir in self._dir_set():
            task_dir.mkdir(parents=True, exist_ok=True)
            self.log.debug(f"Created {task_dir.name} directory `{task_dir}`")

    def clear(self) -> None:
        """Ensure the job's working directory is empty."""
        shutil.rmtree(self.root)
        self.root.mkdir(parents=True)
        self.log.debug(f"Created empty working directory for job `{self.root.name}`")


class RomsJobFileSystem(JobFileSystem):
    COMPILE_TIME_NAME: Literal["roms/compile_time_code"] = "roms/compile_time_code"
    RUNTIME_NAME: Literal["roms/runtime_code"] = "roms/runtime_code"
    INPUT_DATASETS_NAME: Literal["roms/input_datasets"] = "roms/input_datasets"
    CODEBASES_NAME: Literal["roms/codebases"] = "roms/codebases"
    JOINED_OUTPUT_NAME: Literal["joined_output"] = "joined_output"

    compile_time_code_dir: Final[Path]
    """The directory for compile-time code."""

    runtime_code_dir: Final[Path]
    """The directory for runtime code."""

    input_datasets_dir: Final[Path]
    """The directory for input datasets."""

    codebases_dir: Final[Path]
    """The directory for codebases."""

    def __init__(self, root_directory: Path) -> None:
        super().__init__(root_directory)

        self.compile_time_code_dir = (
            self.input_dir / RomsJobFileSystem.COMPILE_TIME_NAME
        )
        self.runtime_code_dir = self.input_dir / RomsJobFileSystem.RUNTIME_NAME
        self.input_datasets_dir = self.input_dir / RomsJobFileSystem.INPUT_DATASETS_NAME
        self.codebases_dir = self.input_dir / RomsJobFileSystem.CODEBASES_NAME
        self.joined_output_dir = self.output_dir / RomsJobFileSystem.JOINED_OUTPUT_NAME

    @override
    def _dir_set(self) -> set[Path]:
        return (
            super()
            ._dir_set()
            .union(
                {
                    self.compile_time_code_dir,
                    self.runtime_code_dir,
                    self.input_datasets_dir,
                    self.codebases_dir,
                    self.joined_output_dir,
                }
            )
        )
