import shutil
from pathlib import Path
from typing import ClassVar, Final, Literal, override

from cstar.base.log import LoggingMixin


class JobFileSystemManager(LoggingMixin):
    """JobFileSystem establishes a common directory structure convention across
    all jobs.
    """

    _INPUT_NAME: ClassVar[Literal["input"]] = "input"
    _WORK_NAME: ClassVar[Literal["work"]] = "work"
    _TASKS_NAME: ClassVar[Literal["tasks"]] = "tasks"
    _LOGS_NAME: ClassVar[Literal["logs"]] = "logs"
    _OUTPUT_NAME: ClassVar[Literal["output"]] = "output"

    root: Final[Path]
    """The root directory of the job. It is provided via user configuration."""

    input_dir: Final[Path]
    """The directory for job inputs, such as datasets, code repositories, and
    runtime configuration.
    """

    work_dir: Final[Path]
    """The directory for job work items, such as shell scripts generated by the
    system."""

    tasks_dir: Final[Path]
    """The directory for subtasks of a job, such as automatic system tasks
    or those generated via transformations of the inputs."""

    logs_dir: Final[Path]
    """The directory for log files created during the job."""

    output_dir: Final[Path]
    """The directory for writing any outputs from the job."""

    def __init__(self, root_directory: Path) -> None:
        """Initialize the job file system.

        Parameters
        ----------
        root_directory : Path
            The root directory that contains all job byproducts.
        """
        self.root = root_directory
        self.input_dir = self.root / self._INPUT_NAME
        self.work_dir = self.root / self._WORK_NAME
        self.tasks_dir = self.root / self._TASKS_NAME
        self.logs_dir = self.root / self._LOGS_NAME
        self.output_dir = self.root / self._OUTPUT_NAME

    def _dir_set(self) -> set[Path]:
        """Return the complete set of directories for the job.

        Returns
        -------
        set[Path]
        """
        return {
            self.input_dir,
            self.work_dir,
            self.tasks_dir,
            self.logs_dir,
            self.output_dir,
        }

    def prepare(self) -> None:
        """Construct the directory tree for the job."""
        for task_dir in self._dir_set():
            task_dir.mkdir(parents=True, exist_ok=True)
            self.log.debug(f"Created {task_dir.name} directory `{task_dir}`")

    def clear(self) -> None:
        """Ensure the job's working directory is empty."""
        shutil.rmtree(self.root)
        self.root.mkdir(parents=True)
        self.log.debug(f"Created empty working directory for job `{self.root.name}`")


class RomsFileSystemManager(JobFileSystemManager):
    _COMPILE_TIME_NAME: ClassVar[Literal["compile_time_code"]] = "compile_time_code"
    _RUNTIME_NAME: ClassVar[Literal["runtime_code"]] = "runtime_code"
    _INPUT_DATASETS_NAME: ClassVar[Literal["input_datasets"]] = "input_datasets"
    _CODEBASES_NAME: ClassVar[Literal["codebases"]] = "codebases"
    _JOINED_OUTPUT_NAME: ClassVar[Literal["joined_output"]] = "joined_output"

    compile_time_code_dir: Final[Path]
    """The directory for compile-time code."""

    runtime_code_dir: Final[Path]
    """The directory for runtime code."""

    input_datasets_dir: Final[Path]
    """The directory for input datasets."""

    _codebases_dir: Final[Path]
    """The directory for codebases."""

    joined_output_dir: Final[Path]
    """The directory for de-partitioned outputs."""

    def __init__(self, root_directory: Path) -> None:
        super().__init__(root_directory)

        self.compile_time_code_dir = self.input_dir / self._COMPILE_TIME_NAME
        self.runtime_code_dir = self.input_dir / self._RUNTIME_NAME
        self.input_datasets_dir = self.input_dir / self._INPUT_DATASETS_NAME
        self._codebases_dir = self.input_dir / self._CODEBASES_NAME
        self.joined_output_dir = self.output_dir / self._JOINED_OUTPUT_NAME

    @override
    def _dir_set(self) -> set[Path]:
        return (
            super()
            ._dir_set()
            .union(
                {
                    self.compile_time_code_dir,
                    self.runtime_code_dir,
                    self.input_datasets_dir,
                    self._codebases_dir,
                    self.joined_output_dir,
                }
            )
        )

    def codebase_subdir(self, key: str) -> Path:
        """Return a codebase subdirectory path.

        Returns
        -------
        str
        """
        return self._codebases_dir / key
