name: cstar-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pooch
  - pyyaml
  - pip
  - ipython
  # docs
  - sphinx
  - nbsphinx
  - sphinx-book-theme
  - sphinxcontrib-bibtex
  - myst-parser
  - pip:
    - readthedocs-sphinx-ext
    - -e "../."
